version: "3.8"

# Run from: C:\mygit\e-com-site\
# Start all: docker-compose up -d
# Start infra only: docker-compose up -d postgres redis rabbitmq
# Stop all: docker-compose down

services:
  # PostgreSQL Database (shared by all services)
  postgres:
    image: postgres:15
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Multiple databases created via init script
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices

  # Redis Cache (shared)
  redis:
    image: redis:7-alpine
    container_name: redis-local
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - microservices

  # RabbitMQ (shared)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      SERVICE_NAME: product-service
      SERVICE_PORT: 8081
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_TTL: 300
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE: inventory.updates
      MOCK_MODE: "false"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8081/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservices

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SERVICE_NAME: user-service
      SERVICE_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_TTL: 86400
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_EXCHANGE: events
      JWT_SECRET: your-secret-key-change-in-production-please
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 1440
      MOCK_MODE: "false"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservices

  # Frontend Service
  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    container_name: frontend-service
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_USER_SERVICE_URL: http://user-service:8080
      NEXT_PUBLIC_PRODUCT_SERVICE_URL: http://product-service:8081
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    restart: unless-stopped
    networks:
      - microservices

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  microservices:
    driver: bridge
version: "3.8"

# Run from: C:\mygit\e-com-site\
# Start all: docker-compose up -d
# Start infra only: docker-compose up -d postgres redis rabbitmq
# Stop all: docker-compose down

# services:
#   # PostgreSQL Database (shared by all services)
#   postgres:
#     image: postgres:15
#     container_name: postgres-local
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       # Multiple databases created via init script
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     networks:
#       - microservices

#   # Redis Cache (shared)
#   redis:
#     image: redis:7-alpine
#     container_name: redis-local
#     command: redis-server --appendonly yes
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 3s
#       retries: 5
#     networks:
#       - microservices

#   # RabbitMQ (shared)
#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq-local
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest
#     ports:
#       - "5672:5672"   # AMQP
#       - "15672:15672" # Management UI
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq
#     healthcheck:
#       test: ["CMD", "rabbitmq-diagnostics", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     networks:
#       - microservices

#   # Product Service
#   product-service:
#     build:
#       context: ./services/product-service
#       dockerfile: Dockerfile
#     container_name: product-service
#     environment:
#       SERVICE_NAME: product-service
#       SERVICE_PORT: 8081
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_NAME: products_db
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#       CACHE_TTL: 300
#       RABBITMQ_HOST: rabbitmq
#       RABBITMQ_PORT: 5672
#       RABBITMQ_USER: guest
#       RABBITMQ_PASSWORD: guest
#       RABBITMQ_QUEUE: inventory.updates
#       MOCK_MODE: "false"
#     ports:
#       - "8081:8081"
#     depends_on:
#       postgres:
#         condition: service_healthy
#       redis:
#         condition: service_healthy
#       rabbitmq:
#         condition: service_healthy
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8081/healthz')"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s
#     networks:
#       - microservices

#   # User Service (uncomment when ready)
#   user-service:
#     build:
#       context: ./services/user-service
#       dockerfile: Dockerfile
#     container_name: user-service
#     environment:
#       SERVICE_NAME: user-service
#       SERVICE_PORT: 8080
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_NAME: users_db
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#       SESSION_TTL: 86400
#       RABBITMQ_HOST: rabbitmq
#       RABBITMQ_PORT: 5672
#       RABBITMQ_USER: guest
#       RABBITMQ_PASSWORD: guest
#       RABBITMQ_EXCHANGE: events
#       JWT_SECRET: your-secret-key-change-in-production
#       MOCK_MODE: "false"
#     ports:
#       - "8080:8080"
#     depends_on:
#       postgres:
#         condition: service_healthy
#       redis:
#         condition: service_healthy
#       rabbitmq:
#         condition: service_healthy
#     restart: unless-stopped
#     networks:
#       - microservices

# volumes:
#   postgres_data:
#   redis_data:
#   rabbitmq_data:

# networks:
#   microservices:
#     driver: bridge