apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cs-samvith/e-commerce
    targetRevision: main
    path: kubernetes/00-base
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true