apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-layer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cs-samvith/e-commerce
    targetRevision: main
    path: kubernetes/01-data-layer
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true